### PR TITLE
Update to 5.0 design

### PR DESCRIPTION
**Pull request by Skruf90**

### CODE REVIEW

**Comment by Skruf90** [comment]
Ah, you havent made build branch yet. Closing this.

**Comment by G-Ray** [comment]
Unfortunately that will not be so easy, we have to reimplement messages send through socket on those files in order to launch commands (start a stream, stop it etc...) on the server.

**Comment by Skruf90** [comment]
That we can fix together :) I have created a build on my fork. So you can just pull it to your repo ~build so we can get started :)

**Comment by G-Ray** [comment]
Beware, I don't think plongflix is released under an open source license...

**Comment by Skruf90** [comment]
Plongflix is my name, so no worries there. I can just release it under open source license

**Pull request closed without merging**
